# 默认参数配置
argOptions: 
  # 字符串或者数组, 参数值是否已字符串返回
  string: [mode, dist] 
  # boolean: 字符串或者数组，参数值是否已boolean值返回
  # 设置别名
  alias: 
    mode: m
    dist: d
  # 默认值
  default: 
    mode: production
    dist: dist

# 服务信息
server:
  # 启动express脚步
  bin: ../../../bin/www
  # nodemon监控文件
  path: 
    - ../../../bin
    - ../../../routes
    - ../../../views/**/*.*
    - ../../../_config.yml
    - ../../../app.js
  # browserSync代理本地服务
  proxy: localhost:3000
  # browserSync端口
  port: 7000
  # browserSync监控文件
  files:
    - ../../../static/**/*.*
  # browserSync忽略监控文件
  ignored:
    - ../../../static/js/bower_components
    - ../../../static/js/grunt
    - ../../../static/js/gulp
    - ../../../static/js/webpack
  browser: google chrome
  open: true
  

# 源文件
src:
  es6: ../src/**/*.es6
  html: ../src/**/*.html
  css: ../src/**/*.css
  baseless: ../commons/less/sti.less
  baselessPath: ../commons/**/*.less
  less: ../src/**/*.less

# 目标文件
dest:
  root: ../dist
  js: ../dist/js
  css: ../dist/css
  cssbase: ../dist/css
  baseCSS: ../dist/css/*.css

# sftp信息
sftp:
  host:
  port:
  user:
  pass:
  remotePath: 